### ISSUE TITLE
Broken, strange code in merge-configs.js

### ISSUE THREAD

**Issue by ensemblebd** [coditorium/nodejs-read-config#2]
`const merge = require('lodash').mergeWith;
module.exports = function(configs) {
    if (!configs || !configs.length) return {};
    return merge({}, ...configs, (a, b) => {
        return Array.isArray(a) ? b : undefined;
    });
};`
Is not valid.

Notice the: 
`return merge({}, ...configs, (a, b) => {`
aka random ellipsis causing gulp failure. Was this plugin tested at all?

After fixing that, and playing around with paths, was able to get it to work perfectly, and am quite happy with your plugin. Thank you

**Comment by prometheas** [comment]
@ensemblebd - if I'm reading this correctly, it sounds like you've fixed a bug; have you attempted to offer a PR?

**Comment by ensemblebd** [comment]
Yes sir, I basically just forked it and have been using my own repo recently. 
Just submitted a PR. :)

**Comment by ensemblebd** [comment]
Just to confirm , sorry I know this is WAY over due. But it turns out the issue was the result of running an old version of node that did not support the "..." syntax. Well technically it was an environment variable path issue, but point is, it was running the wrong version of node for my project.

This issue is a non-issue and should be closed. Apologies for any confusion or wasted time!

**Comment by pmendelski** [comment]
@ensemblebd thanks for closing this issue
